stages:
- build
- update

before_script:
- docker info
- docker logout $CI_REGISTRY
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --no-cache -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME $CI_REGISTRY_IMAGE
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - /^v.*$/

update:
  stage: update
  tags:
    - dellvms-ssh
  script:
    - ssh 192.168.10.252 'docker pull docker.datumcorp.com/datum/m4-python-services && docker stop psdev && docker rm -f -v psdev && docker run -d --name psdev -p 8000:8000 docker.datumcorp.com/datum/m4-python-services'
  only:
    - /^v.*$/